// main tools
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

// components
import { Toaster } from '@/components/atoms/toast';

// providers
import { Providers } from './providers';

// utils
import { cn } from '@/lib/utils';

// styles
import './globals.css';
import { Typography } from '@/components/atoms/typography';

const inter = Inter({ subsets: ['latin'], variable: '--font-main' });

export const metadata: Metadata = {
	icons: '/assets/job.png',
	title: 'Todo Location App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased relative',
					inter.variable,
				)}
			>
				<Providers>{children}</Providers>
				<Toaster position='top-center' />
				<footer className='absolute bottom-2 left-2'>
					<Typography fontSize='minimum' weight='medium' color='foreground'>
						Made by Rouchjq & Lehafari
					</Typography>
				</footer>
			</body>
		</html>
	);
}
