// main tools
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

// providers
import { Providers } from './providers';

// utils
import { cn } from '@/lib/utils';

// styles
import './globals.css';
import { Toaster } from '@/components/atoms/toast';

const inter = Inter({ subsets: ['latin'], variable: '--font-main' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn('bg-background font-sans antialiased', inter.variable)}>
				<Providers>{children}</Providers>
				<Toaster position='top-center' />
			</body>
		</html>
	);
}
